apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-world
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
        - name: node-hello-world
          image: medeiser/node-hello-world:REPLACEME
          ports:
            - containerPort: 8080
          env:
            - name: ENV_NODE
              value: REPLACEME
