apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-hello-world
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: node-hello-world
    spec:
      containers:
        - name: node-hello-world
          image: medeiser/node-hello-world:REPLACEME
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: node-hello-world-env
                  key: NODE_ENV
          volumeMounts:
            - name: config-volume
              mountPath: /usr/src/app/config
              subPathExpr: $(NODE_ENV).yaml
            - name: common-config-volume
              mountPath: /usr/src/app/config
              subPathExpr: $common-$(NODE_ENV).yaml
      volumes:
        - name: config-volume
          configMap:
            name: node-hello-world-config
        - name: common-config-volume
          configMap:
            name: common-config