apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ../../../config/overlays/dev

images:
- name: medeiser/node-hello-world
  newTag: '4'

configMapGenerator:
  - name: node-hello-world-env
    literals:
      - NODE_ENV="dev"
  - name: node-hello-world-config
    files:
      - config/dev.yaml
      